### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by kevinji** [sylvia43/JourneyOfFear#11]
[`singleplayer_info.txt`](https://github.com/anubiann00b/JourneyOfFear/blob/master/info/singleplayer_info.txt) refers to a LICENSE, but no LICENSE exists for this project. Probably throwing in the GPLv3 or the MIT license would be fine, depending on what you want.

**Comment by ghost** [comment]
Done.

**Comment by kevinji** [comment]
Hmm I don't know if MIT is actually the license you want, considering that it allows the end user to distribute the project at will. Try using [ChooseaLicense.com](http://choosealicense.com/).

**Comment by MirrorImage** [comment]
Apparently he wants the MIT. I tried changing it to Apache, but nonetheless got reverted.
