### ISSUE TITLE
In the newest release, this.

### ISSUE THREAD

**Issue by MirrorImage** [sylvia43/JourneyOfFear#14]
![ground breaking glitch](https://cloud.githubusercontent.com/assets/5495335/2874104/1f503846-d3d6-11e3-9a6e-00ff3c005037.PNG)

**Comment by ghost** [comment]
IKR. Something got screwed up. Not me.

**Comment by sylvia43** [comment]
How long did you play? (by the way if you still had health remaining I would immediately start worshipping you).

**Comment by sylvia43** [comment]
Fixed.
