### ISSUE TITLE
Loop error

### ISSUE THREAD

**Issue by MirrorImage** [sylvia43/JourneyOfFear#25]
There's a massive pause after each song. It kind of ruins the fact that they're loopable.

**Comment by sylvia43** [comment]
What do you mean? I gave a one second pause between songs, yeah, but only because it chooses a new one.

**Comment by MirrorImage** [comment]
Didn't I make the songs loopable to play them continuously per area? A playlist isn't exactly how games really work.

**Comment by sylvia43** [comment]
Run escape though.

**Comment by MirrorImage** [comment]
I recently ran the game again. It's still super delayed. I timed each. After around 2 to 4 songs, it doesn't loop anymore. The delay is from 14 seconds in the least to 3 minutes 53 seconds at most.
Run on a Intel quad core i5 processor.

**Comment by RobUnderscore** [comment]
Gave a shot at a fix, appears to be working fine for me (Linux and Windows).

https://github.com/anubiann00b/JourneyOfFear/pull/26
