### ISSUE TITLE
Layering FAIL

### ISSUE THREAD

**Issue by ghost** [sylvia43/JourneyOfFear#6]
Enemies on one section don't show up in another section, but can still attack you.
https://onedrive.live.com/redir?resid=8D4BD1B8EEE20F7A!3488&authkey=!AEhPW_ROsbQt7Hs&ithint=video%2c.mp4
Here's the video.

**Comment by ghost** [comment]
I will work on it, but I wasn't the one who made the code...

**Comment by sylvia43** [comment]
_facepalm_ that sounds like a stupid mistake, I'll try to fix it...

**Comment by sylvia43** [comment]
Oh this is because I don't update the currentArea field of renderer...
