### ISSUE TITLE
Menu Screen Boxes

### ISSUE THREAD

**Issue by ghost** [sylvia43/JourneyOfFear#7]
Menu screen boxes are bugged. Pictures attached.
![screenshot from 2014-03-05 13 40 22](https://f.cloud.github.com/assets/5723421/2339137/bac9677e-a4b1-11e3-8975-9cc830242419.png)
![screenshot from 2014-03-05 13 40 31](https://f.cloud.github.com/assets/5723421/2339138/bacb3306-a4b1-11e3-8036-fe8b4eb6acd0.png)

**Comment by ghost** [comment]
The bottom picture is supposed to be of my mouse in the box but not triggering the animation...

**Comment by sylvia43** [comment]
Umm when you mouse over they become transparent, that's number one... I think the natives are messed up somehow...

**Comment by ghost** [comment]
That's my driver bug. Ignore it.

**Comment by sylvia43** [comment]
Ok I can't duplicate this, it's probably the natives... also can you elaborate on the pictures? Are the buttons sticking? I would assume it's because of how linux handles the window and mouse...

**Comment by sylvia43** [comment]
Why is Brennan assigned to this?

**Comment by ghost** [comment]
Brennan made the menu... The first one is me selecting two boxes, and the
second one is supposed to be of my mouse in the box, but not triggering the
anim. Check the bounding boxes or something.

**Comment by sylvia43** [comment]
Oh I did the menu, Brennan did the art. I think the bounding boxes are slightly off; only slightly though.

**Comment by sylvia43** [comment]
I can't see your mouse cursor in either screen...

**Comment by ghost** [comment]
The joys of screenshots.

**Comment by sylvia43** [comment]
Can you take a clearer screenshot?

**Comment by ghost** [comment]
Sure

**Comment by sylvia43** [comment]
Is this still an issue; and can you clarify?

**Comment by ghost** [comment]
Check the clickboxes... IDK.

**Comment by MirrorImage** [comment]
This isn't an issue in that alpha release you made, so I guess this issue can be closed?
