### ISSUE TITLE
Inventory

### ISSUE THREAD

**Issue by MirrorImage** [sylvia43/JourneyOfFear#8]
WORK ON THE INVENTORY SHREYAS
I SWEAR TO GOD

**Comment by sylvia43** [comment]
This is todo, todo goes in the todo, not in the issues. Issues are for bugs, questions, and repository management,

**Comment by ghost** [comment]
LOL well played.

**Comment by sylvia43** [comment]
Message me or yell at me in person, that way I can ignore you easily.
